# Generated by Django 4.0 on 2021-12-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_support', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['id', 'ticket_theme', 'creation_date', 'last_update', 'is_answered', 'last_answer_date']},
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='last_support_answer',
            new_name='last_answer_date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='answered',
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
    ]
