# Generated by Django 4.0 on 2021-12-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_support', '0002_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='not_answered_time',
            field=models.IntegerField(default=0),
        ),
    ]
