# Generated by Django 4.0 on 2021-12-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_support', '0003_ticket_not_answered_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='not_answered_time',
        ),
        migrations.AddField(
            model_name='appuser',
            name='max_not_answered_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
