# Generated by Django 4.0 on 2021-12-16 20:22

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app_support', '0004_remove_ticket_not_answered_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'ordering': ['max_not_answered_seconds', 'id']},
        ),
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
                ('some_field', django.db.models.manager.Manager()),
            ],
        ),
    ]
