# Generated by Django 4.0 on 2021-12-16 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_support', '0005_alter_appuser_options_alter_appuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
            ],
        ),
    ]
