# Generated by Django 4.0 on 2021-12-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_support', '0006_alter_appuser_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'ordering': ['earliest_unanswered_ticket_answer_date', 'id']},
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='last_answer_date',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='max_not_answered_seconds',
        ),
        migrations.AddField(
            model_name='appuser',
            name='earliest_unanswered_ticket_answer_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='last_answer_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
