# Generated by Django 4.0 on 2021-12-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_support', '0007_alter_appuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['id', 'ticket_theme', 'creation_date', 'last_update', 'is_answered']},
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='last_answer_date',
            new_name='user_question_date',
        ),
        migrations.AddField(
            model_name='ticket',
            name='messages_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='was_closed_by',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
