# Generated by Django 4.0 on 2021-12-16 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_support', '0008_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'ordering': ['earliest_unanswered_ticket_question_date', 'id']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['id', 'ticket_theme', 'creation_date', 'last_changes', 'is_answered']},
        ),
        migrations.RenameField(
            model_name='appuser',
            old_name='earliest_unanswered_ticket_answer_date',
            new_name='earliest_unanswered_ticket_question_date',
        ),
        migrations.RenameField(
            model_name='appuser',
            old_name='last_update',
            new_name='last_changes',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='last_update',
            new_name='last_changes',
        ),
    ]
