# Generated by Django 4.0 on 2021-12-17 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_support', '0009_alter_appuser_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['id', 'ticket_theme', 'user_question_date', 'last_changes', 'is_answered']},
        ),
    ]
