# Generated by Django 4.0 on 2021-12-17 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_support', '0010_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'ordering': ['max_unanswered', 'id']},
        ),
        migrations.RenameField(
            model_name='appuser',
            old_name='earliest_unanswered_ticket_question_date',
            new_name='max_unanswered',
        ),
    ]
