# Generated by Django 4.0 on 2021-12-17 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_support', '0011_alter_appuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'ordering': ['unanswered', 'id']},
        ),
        migrations.RenameField(
            model_name='appuser',
            old_name='max_unanswered',
            new_name='unanswered',
        ),
    ]
