# Generated by Django 4.0 on 2021-12-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_support', '0013_alter_appuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='opened_tickets_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
