# Generated by Django 4.0 on 2021-12-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_support', '0014_alter_appuser_opened_tickets_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='was_closed_by',
        ),
        migrations.AddField(
            model_name='appuser',
            name='tickets_messages',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='answerer_id',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='closed_by_id',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user_question_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
