# Generated by Django 4.0 on 2021-12-18 13:43

import app_support.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_support', '0015_remove_ticket_was_closed_by_appuser_tickets_messages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='linked_user',
            field=models.ForeignKey(on_delete=models.SET(app_support.models.get_current_tc_user_object), related_name='messages', related_query_name='message', to='app_support.appuser'),
        ),
    ]
