# Generated by Django 4.0 on 2021-12-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_support', '0016_alter_message_linked_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tmp_is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
