# Generated by Django 4.0 on 2021-12-18 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_support', '0017_ticket_tmp_is_closed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='tmp_is_closed',
            new_name='_tpm_is_closed',
        ),
    ]
