# Generated by Django 4.0 on 2021-12-18 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_support', '0018_rename_tmp_is_closed_ticket__tpm_is_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='_tpm_is_closed',
        ),
    ]
